### ISSUE TITLE
Bug on Last Level

### ISSUE THREAD

**Issue by EricEisaman** [IKStreamIvo/Bubble-Bobble-Clone#1]
Once the last level has been reached, you can go out the top of the level map and jump down on the far left or far right.  This also happens for the enemies.  In the case an enemy jumps out of the center map zone, you can never complete the level unless you venture out there as well.
![bubble-bobble](https://user-images.githubusercontent.com/6116865/41291094-c0c25aa8-6e1c-11e8-834c-4f57fd7f2da3.png)

**Comment by JP18** [comment]
To fix this problem, I would either add more blocks at the top or lower the high platforms.

**Comment by Ivolutio** [comment]
I lowered the platform and I added a check that kills the player/enemy if they're out of the level.
